config/routes.rb
Rails.application.routes.draw do
  root "recipes#index"

  resources :recipes do 
    resources :ratings
    resources :tags
  end 
  resources :ingredients

  get "tags/:tag", to: "recipe#show", as: :tag
  get "/search", to: "ingredients#search"
  get "/sorted", to: "ratings#sorted"
end

app/models/IngredientsRecipe.rb
class IngredientsRecipe < ApplicationRecord
    belongs_to :recipe
    belongs_to :ingredient
end

app/models/RecipesTag.rb
class RecipesTag < ApplicationRecord
    belongs_to :tag
    belongs_to :recipe
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/ingredient.rb
class Ingredient < ApplicationRecord
    has_many :ingredients_recipes, class_name: 'IngredientsRecipe', dependent: :destroy
    has_many :recipes, through: :ingredients_recipes, dependent: :destroy

    validates :body, presence: true 
end

app/models/rating.rb
class Rating < ApplicationRecord
  belongs_to :recipe

  validates :body, presence: true 
end

app/models/recipe.rb
class Recipe < ApplicationRecord
    has_one :rating, dependent: :destroy

    has_many :recipe_tags, class_name: 'RecipesTag', dependent: :destroy
    has_many :tags, through: :recipe_tags

    has_many :ingredients_recipes, class_name: 'IngredientsRecipe', dependent: :destroy
    has_many :ingredients, through: :ingredients_recipes

    accepts_nested_attributes_for :tags, :rating, allow_destroy: true 
    
    validates :title, presence: true 
    validates :body, presence: true
end

app/models/tag.rb
class Tag < ApplicationRecord

    has_many :recipe_tags, class_name: 'RecipesTag', dependent: :destroy
    has_many :recipes, through: :recipe_tags, dependent: :destroy

    validates :title, presence: true 
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/ingredients_controller.rb
class IngredientsController < ApplicationController

    def index
        @ingredients = Ingredient.all
    end

    def search 
        if params[:search_by_ingredients].downcase && params[:search_by_ingredients].downcase != ""
            @recipes = Recipe.joins(:ingredients).where("ingredients.body LIKE ?", params[:search_by_ingredients])
        end
    end 

    def show 
        @ingredient = Ingredient.find(params[:id])
    end 

    def new 
        @ingredient = Ingredient.new 
    end

    def create
        @ingredient = Ingredient.new(ingredient_params)

        if @ingredient.save 

            redirect_to ingredients_path
        else
            render :new 
        end 
    end 

    def destroy 
        @ingredient = Ingredient.find(params[:id])
        @ingredient.destroy 

        redirect_to root_path 
    end 

    private 
    def ingredient_params 
        params.require(:ingredient).permit(:body, :id)
    end

    def recipe_params
        params.permit(:title)
    end 

    
end

app/controllers/ratings_controller.rb
class RatingsController < ApplicationController
    
    def create 
        @recipe = Recipe.find(params[:recipe_id])
        @rating = @recipe.create_rating!(rating_params)
        redirect_to recipe_path(@recipe)
    end 

    private 
        def rating_params
            params.require(:rating).permit(:body)
        end 
end

app/controllers/recipes_controller.rb
class RecipesController < ApplicationController

    def index 
        @recipes = Recipe.all.joins(:rating).order("ratings.body DESC")
    end 

    def show 
        @recipe = Recipe.find(params[:id])
    end 

    def new 
        @recipe = Recipe.new 
    end 

    def create
        @recipe = Recipe.new(recipe_params)

        if @recipe.save!
            redirect_to @recipe
        else
            render :new
        end 
    end 

    def edit 
        @recipe =  Recipe.find(params[:id])
    end 

    def update 
        @recipe = Recipe.find(params[:id])

        if @recipe.update(recipe_params)
            redirect_to @recipe
        else 
            render :edit 
        end 
    end 

    def destroy 
        @recipe = Recipe.find(params[:id])
        @recipe.destroy 

        redirect_to root_path 
    end

    private 
        def recipe_params
            params.require(:recipe).permit(:title, :body, ingredient_ids:[])
        end

end

app/controllers/tags_controller.rb
class TagsController < ApplicationController

    def index
        @tags = Tag.all
    end

    def show 
        @tag = Tag.find(params[:id])
        @recipe = Recipe.find(params[:recipe_id])
    end 

    def new 
        @tag = Tag.new 
        @recipe = Recipe.find(params[:recipe_id])
    end

    def create
        @recipe = Recipe.find(params[:recipe_id])
        @tag = Tag.find_or_create_by(tag_params)
        @tag.recipe_tags.create!(recipe_id: params[:recipe_id])

        if @tag.save!
            redirect_to @recipe
        else
            render :new 
        end 

    end 

    def edit 
        @tag = Tag.find(params[:tag_id])
        @recipe = Recipe.find(params[:recipe_id])
    end 

    def update 
        @tag = Tag.find(params[:id])
        @recipe = Recipe.find(params[:recipe_id])

        if @tag.update!(tag_params)
            redirect_to @recipe
        else 
            render :edit 
        end 
    end 

    def destroy 
        @tag = Tag.find(params[:tag_id])
        @tag.destroy

        redirect_to root_path
    end 

    private 
        def tag_params 
            params.require(:tag).permit(:title)
        end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/ingredients_helper.rb
module IngredientsHelper
end

app/helpers/ratings_helper.rb
module RatingsHelper
end

app/helpers/recipes_helper.rb
module RecipesHelper
end

app/helpers/tags_helper.rb
module TagsHelper
end

app/views/ingredients/_form.html.erb
<%= form_with model: @ingredient do |form| %>
        <div>
            <%= form.label :Ingredient %><br>
            <%= form.text_area :body %>
        </div>

        <div>
            <%= form.submit %>
        </div>
<% end %> 

app/views/ingredients/index.html.erb
<h1>All Ingredients</h1>

<div>
    <% @ingredients.each do |ingredient| %>
        <li><%= link_to ingredient.body, ingredient %></li> 
    <% end %>
</div><br>

<%= link_to "Add Ingredients", new_ingredient_path %><br>
<%= link_to "Home", "/recipes" %><br>

<%= form_tag "/search", method: "GET" do %>
    <%= label_tag :search_by_ingredients %>
    <%= text_field_tag :search_by_ingredients, params[:search_by_ingredients] %>

    <%= submit_tag "Search" %>
<% end %>

app/views/ingredients/new.html.erb
<h1>New Ingredients</h1>

<%= render "form", ingredient: @ingredient %> <br>

<%= link_to "View Ingredients", ingredients_path %><br>
<%= link_to "Home", "/recipes" %>

app/views/ingredients/search.html.erb
<h1>Search results</h1>

<% if @recipes.present? %>
    <% @recipes.each do |recipe| %>
        <%= link_to recipe.title, recipe %><br>
    <% end %><br>
<% else %>
    <p>No result found</p><br>
<% end %>

<%= link_to "Home", "/recipes" %>

app/views/ingredients/show.html.erb
<h1>Ingredient: <%= @ingredient.body %></h1>


<%= link_to "Destroy Ingredient", ingredient_path, 
                method: :delete,
                data: { confirm: "Are you sure?" } %><br>
<%= link_to "Home", "/recipes" %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RecipeBox</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/ratings/_form.html.erb
<%= form_with model: [@recipe, @recipe.build_rating] do |form| %>
    <div>
        <%= form.label :rating %><br>
        <%= form.text_area :body %>
    </div>

    <div>
        <%= form.submit %>
    </div>
<% end %> 

app/views/recipes/_form.html.erb
<div>
<%= form_with model: @recipe do |form| %>
    <div>
        <%= form.label :title %><br>
        <%= form.text_field :title %>
    </div><br>

    <div>
        <%= form.label "Choose your ingredients: " %><br>
            <%= form.collection_check_boxes :ingredient_ids, Ingredient.all, :id, :body do |x| %>
                <%= x.check_box %>
                <%= x.label %><br>
            <% end %> 
    </div> <br>
    
    <div>
        <%= form.label :Instructions %><br>
        <%= form.text_area :body %>
    </div><br>

    <div>
        <%= form.submit %>
    </div>
<% end %><br>

<h2><%= link_to "Home", root_path %></h2>

</div>

app/views/recipes/edit.html.erb
<h1>Edit Recipes</h1>

<%= render "form", recipe: @recipe %> 

app/views/recipes/index.html.erb
<h1>My Recipes</h1>

<div>
    <% @recipes.each do |recipe| %>

        <h2><%= link_to recipe.title, recipe %></h2>
        <p><%= truncate(recipe.body, length: 50) %></p>
        <p><small>Tags: <% recipe.tags.each do |tag| %><%= tag.title %><% end %> </small></p>

    <% end %>
</div>

<h2><%= link_to "New Recipe", new_recipe_path %></h2>

<%= link_to "Add Ingredients", new_ingredient_path %><br>
<%= link_to "View Ingredients", ingredients_path %>

app/views/recipes/new.html.erb
<h1>New Recipe</h1>

<%= render "form", recipe: @recipe %> 

app/views/recipes/show.html.erb
<h1><%= @recipe.title %></h1>

<%@recipe.tags.each do |tag|%>
    <%= link_to tag.title, recipe_tag_path(@recipe, tag)%>
<% end %>

<% if @recipe.rating.present? %>

    <h2>Rating: <%= @recipe.rating.body %>/5</h2>

<% else %> 

    <h2>Set Rating out of 5 for <%= @recipe.title %></h2>

    <%= render "ratings/form" %>

<% end %> 

<h1>Ingredients</h1>

<%@recipe.ingredients.each do |ingredient|%>
    <li>
        <%= ingredient.body%>
    </li>
<% end %><br>

<h1>Instructions: </h1>
<p> <%= @recipe.body %></p>



<br>


<%= link_to "New Tag", new_recipe_tag_path(@recipe)%><br>
<%= link_to "Edit Recipe", edit_recipe_path(@recipe) %><br>
<%= link_to "Destroy Recipe", recipe_path(@recipe), 
                method: :delete,
                data: { confirm: "Are you sure?" } %><br>
<%= link_to "Home", "/recipes" %>

app/views/tags/_form.html.erb
<%= form_with model: [recipe, tag] do |form| %>
    <div>
        <%= form.label :Tag %><br>
        <%= form.text_field :title %>
    </div>

    <div>
        <%= form.submit %>
    </div>
<% end %>

app/views/tags/edit.html.erb
<h1>Edit Tag</h1>

<%= render "form", { tag: @tag, recipe: @recipe } %> 

app/views/tags/index.html.erb
<%= render @tags%>

app/views/tags/new.html.erb
<h1>New Tag</h1>

<%= render "form", { tag: @tag, recipe: @recipe } %> 

app/views/tags/show.html.erb
<h1>What would you like to do for tag: <%= @tag.title %></h1>

<br>

<div>
<%= link_to "Edit Tag", edit_recipe_tag_path(recipe_id: @recipe.id, tag_id: @tag.id)%><br>
<%= link_to "Destroy", recipe_tag_path(recipe_id: @recipe.id, tag_id: @tag.id), 
                method: :delete,
                data: { confirm: "Are you sure?" } %><br>
<%= link_to "Home", root_path %>
</div>